# Generated by Django 4.0.1 on 2022-01-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
    ]
