# Generated by Django 4.0.3 on 2022-04-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smalldrf', '0002_forclassview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forclassview',
            old_name='lname',
            new_name='lna',
        ),
        migrations.RenameField(
            model_name='forclassview',
            old_name='name',
            new_name='na',
        ),
    ]
