# Generated by Django 4.0.1 on 2022-02-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.group')),
            ],
        ),
    ]
